// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8ypMkC4pWrfX84ihDwCsQzRFO-cI7gLA',
    appId: '1:738791211618:web:3e7b9e96f58c9e0da1473b',
    messagingSenderId: '738791211618',
    projectId: 'easytour-10c85',
    authDomain: 'easytour-10c85.firebaseapp.com',
    storageBucket: 'easytour-10c85.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBELJ5ERlDzzIvo8DjcwGDisk8IEI1I0yE',
    appId: '1:738791211618:android:12f03e9008fb36c3a1473b',
    messagingSenderId: '738791211618',
    projectId: 'easytour-10c85',
    storageBucket: 'easytour-10c85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC1r3Y6qS5Xqi2-O1Cc_R5y-fNl8cdXl0',
    appId: '1:738791211618:ios:43d8890a26f38755a1473b',
    messagingSenderId: '738791211618',
    projectId: 'easytour-10c85',
    storageBucket: 'easytour-10c85.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC1r3Y6qS5Xqi2-O1Cc_R5y-fNl8cdXl0',
    appId: '1:738791211618:ios:43d8890a26f38755a1473b',
    messagingSenderId: '738791211618',
    projectId: 'easytour-10c85',
    storageBucket: 'easytour-10c85.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8ypMkC4pWrfX84ihDwCsQzRFO-cI7gLA',
    appId: '1:738791211618:web:af4ad0970e49280ba1473b',
    messagingSenderId: '738791211618',
    projectId: 'easytour-10c85',
    authDomain: 'easytour-10c85.firebaseapp.com',
    storageBucket: 'easytour-10c85.appspot.com',
  );
}
